Thank you guys for your cooperation
STAC-IITMandi/astrax.in pull request #41
Opened 2021-04-11 09:49 UTC by yuvraj-aseri

2021-04-11 10:25 UTC, gajrajgchouhan requested changes

2021-04-11 10:25 UTC, gajrajgchouhan commented on index.html
> +
Since we already have font-awesome (see above) and the font isn't being used these can be removed.

2021-04-11 10:25 UTC, gajrajgchouhan commented on index.html
> +
Whitspaces can be removed and can you change the id to something related to its function (for eg `id="go-to-top"`). Also  then move the anchor tag to somewhere near top of the `<body>`

2021-04-11 14:02 UTC, gajrajgchouhan approved these changes
Nice work @yuvraj-aseri ! Thank you for the PR! :rocket:

2021-04-11 17:47 UTC, harnaman-hk requested changes
Following improvements would be good
1. Centre the ^ symbol within the circle
2. Size of circle can be reduced, it is slightly larger than convenient for mobile view
3. Use the darker shade of blue in the background gradient

2021-04-14 04:48 UTC, harnaman-hk commented
@yuvraj-aseri  Looks good!
@gajrajgchouhan If you don't have any comments, we can merge it soon.

2021-04-14 04:48 UTC, harnaman-hk approved these changes

2021-04-14 05:38 UTC, merged